ComptageMaker\ComptageBundle\Entity\Comptage:
    type: entity
    table: null
    repositoryClass: ComptageMaker\ComptageBundle\Entity\ComptageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        briefing:
            type: datetime
        etat:
            type: boolean

        comment:
            type: text
            nullable: true

        date:
            type: date

    oneToMany:
      sessions:
        targetEntity: Session
        mappedBy: comptage
    lifecycleCallbacks: {  }
