ComptageMaker\ComptageBundle\Entity\Comptage:
    type: entity
    table: null
    repositoryClass: ComptageMaker\ComptageBundle\Entity\ComptageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        briefing:
            type: datetime
        etat:
            type: boolean

        date:
            type: date

    manyToMany:
      sessions:
        targetEntity: Session
        joinTable:
          name: comptages_sessions
          joinColumns:
            comptage_id:
              referencedColumnName: id
          inverseJoinColumns:
            session_id:
              referencedColumnName: id
              unique: true

    lifecycleCallbacks: {  }
