ComptageMaker\ComptageBundle\Entity\Entries:
    type: entity
    table: null
    repositoryClass: ComptageMaker\ComptageBundle\Entity\EntriesRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        valeur:
            type: integer
    lifecycleCallbacks: {  }


    oneToOne:
        plage:
          targetEntity: Plage