ComptageMaker\ComptageBundle\Entity\Inscrit:
    type: entity
    table: null
    repositoryClass: ComptageMaker\ComptageBundle\Entity\InscritRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        voiture:
            type: boolean
        commentaires:
            type: text
            nullable: true


    manyToOne:
        association:
          targetEntity: Association
          joinColumn:
            name: association_id
            referencedColumnName: id

    lifecycleCallbacks: {  }
