ComptageMaker\ComptageBundle\Entity\TextBlock:
    type: entity
    table: null
    repositoryClass: ComptageMaker\ComptageBundle\Entity\TextBlockRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
            nullable: true

        title:
            type: string
            length: 255

    lifecycleCallbacks: {  }
