<?php

namespace ComptageMaker\ComptageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageRepository extends EntityRepository
{
}
