comptage_maker_comptage_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ComptageMakerComptageBundle:Default:index }

comptage_home:
    pattern: /
    defaults: { _controller: ComptageMakerComptageBundle:Text:home }


comptage_faq:
    pattern: /faq
    defaults: { _controller: ComptageMakerComptageBundle:Text:faq }

comptage_login:
    pattern: /login
    defaults: { _controller: ComptageMakerComptageBundle:Admin:login }

comptage_login_check:
    pattern: /login_check

logout:
    pattern: /logout

comptage_list:
    pattern: /list
    defaults: { _controller: ComptageMakerComptageBundle:Comptage:listCount }

comptage_change_status:
    pattern: /count/{id}/change
    defaults: { _controller: ComptageMakerComptageBundle:Comptage:changeStatus }

comptage_edit:
    pattern: /count/{id}/edit
    defaults: { _controller: ComptageMakerComptageBundle:Comptage:edit }

comptage_create:
    pattern: /count/create
    defaults: { _controller: ComptageMakerComptageBundle:Comptage:create }