comptage_maker_association:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/association/routing.yml"
    prefix:   /association

comptage_maker_count:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/count/routing.yml"
    prefix:   /count

comptage_maker_inscrit:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/inscrit/routing.yml"
    prefix: /inscrit

comptage_maker_plage:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/plage/routing.yml"
    prefix: /plage

comptage_maker_session:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/session/routing.yml"
    prefix: /session

comptage_maker_textblock:
    resource: "@ComptageMakerComptageBundle/Resources/config/Entity/textblock/routing.yml"
    prefix: /textblock

comptage_maker_comptage_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ComptageMakerComptageBundle:Default:index }

comptage_home:
    pattern: /
    defaults: { _controller: ComptageMakerComptageBundle:TextBlock:home }


comptage_faq:
    pattern: /faq
    defaults: { _controller: ComptageMakerComptageBundle:Text:faq }

comptage_login:
    pattern: /login
    defaults: { _controller: ComptageMakerComptageBundle:Admin:login }

comptage_login_check:
    pattern: /login_check

logout:
    pattern: /logout

comptage_list:
    pattern: /list
    defaults: { _controller: ComptageMakerComptageBundle:Comptage:listCount }


admin_dashboard:
    pattern: /admin/dashboard
    defaults: { _controller: ComptageMakerComptageBundle:Admin:dashBoard }