parameters:
#    comptage_maker_comptage.example.class: ComptageMaker\ComptageBundle\Example

services:
#    comptage_maker_comptage.example:
#        class: %comptage_maker_comptage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
