ComptageMaker\ComptageBundle\Entity\Inscrit:
    properties:
        nom:
            - NotBlank: ~
        prenom:
            - NotBlank: ~
        mail:
            - NotBlank: ~
        tel:
            - NotBlank: ~
            - Regex:
                pattern: "/^0[6-7]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})/"
                message: "Seuls les téléphones portables sont valides (06 ou 07)"